---
name: http-producer

server:
  applicationConnectors:
    - type: http
      port: ${APPLICATION_PORT:-18080}
  adminConnectors:
    - type: http
      port: ${ADMIN_PORT:-18081}

kafka:
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:-127.0.0.1:9092}